def node_require(script)
  require Pod::Executable.execute_command(
    'node',
    [
      '-p',
      "require.resolve(
        '#{script}',
        {paths: [process.argv[1]]},
      )",
      __dir__
    ]
  ).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, '18.0'

prepare_react_native_project!

use_modular_headers!

setup_permissions([
  'Camera',
  'FaceID',
  'LocationAccuracy',
  'LocationAlways',
  'LocationWhenInUse',
  'Notifications',
  'PhotoLibrary',
  'PhotoLibraryAddOnly',
])

target 'ToutRoutesApp' do

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|

    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Force iOS 18 and C++20 for all Pods
    installer.pods_project.targets.each do |target|

      target.build_configurations.each do |build_config|

        build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.0'
        build_config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
        build_config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'

        build_config.build_settings[
          'CLANG_WARN_NON_MODULAR_INCLUDE_IN_FRAMEWORK_MODULE'
        ] = 'NO'

      end
    end

    # React Native / C++ dependencies
    [
      'React',
      'React-Core',
      'ReactCommon',
      'React-utils',
      'React-runtimescheduler',
      'React-runtimeexecutor',
      'React-rendererdebug',
      'React-perflogger',
      'React-featureflags',
      'React-debug',
      'React-RCTFabric',
      'React-RCTFBReactNativeSpec',
      'Yoga',
      'hermes-engine',
      'fmt',
      'RCT-Folly',
      'boost',
      'fast_float',
      'glog',
      'DoubleConversion'
    ].each do |pod_name|

      target = installer.pods_project.targets.find do |t|
        t.name == pod_name
      end

      next unless target

      target.build_configurations.each do |build_config|

        build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.0'
        build_config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
        build_config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'

      end
    end

  end

end
